FROM golang:1.26.2-alpine AS builder

WORKDIR /application

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /application/payment-service ./cmd/payment

FROM alpine:3.23

WORKDIR /application

RUN addgroup -S application && adduser -S application -G application

COPY --from=builder /application/payment-service ./payment-service

USER application

EXPOSE 3001

CMD ["./payment-service"]
