// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createPaymentInboxMessage = `-- name: CreatePaymentInboxMessage :exec
INSERT INTO inbox_messages (message_id, processed_at) VALUES ($1, $2)
`

type CreatePaymentInboxMessageParams struct {
	MessageID   string    `json:"message_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

func (q *Queries) CreatePaymentInboxMessage(ctx context.Context, arg CreatePaymentInboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentInboxMessage, arg.MessageID, arg.ProcessedAt)
	return err
}

const createPaymentOutboxMessage = `-- name: CreatePaymentOutboxMessage :exec
INSERT INTO outbox_messages (id, message_type, routing_key, payload, attempts, next_attempt_at, published_at, last_error, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreatePaymentOutboxMessageParams struct {
	ID            string          `json:"id"`
	MessageType   string          `json:"message_type"`
	RoutingKey    string          `json:"routing_key"`
	Payload       json.RawMessage `json:"payload"`
	Attempts      int32           `json:"attempts"`
	NextAttemptAt time.Time       `json:"next_attempt_at"`
	PublishedAt   sql.NullTime    `json:"published_at"`
	LastError     string          `json:"last_error"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) CreatePaymentOutboxMessage(ctx context.Context, arg CreatePaymentOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentOutboxMessage,
		arg.ID,
		arg.MessageType,
		arg.RoutingKey,
		arg.Payload,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.PublishedAt,
		arg.LastError,
		arg.CreatedAt,
	)
	return err
}

const listPendingPaymentOutboxMessages = `-- name: ListPendingPaymentOutboxMessages :many
SELECT id, message_type, routing_key, payload, attempts, next_attempt_at, published_at, last_error, created_at
FROM outbox_messages WHERE published_at IS NULL AND next_attempt_at <= $1
ORDER BY created_at LIMIT $2 FOR UPDATE SKIP LOCKED
`

type ListPendingPaymentOutboxMessagesParams struct {
	NextAttemptAt time.Time `json:"next_attempt_at"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListPendingPaymentOutboxMessages(ctx context.Context, arg ListPendingPaymentOutboxMessagesParams) ([]OutboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPaymentOutboxMessages, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxMessage{}
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.RoutingKey,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.PublishedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentOutboxFailed = `-- name: MarkPaymentOutboxFailed :exec
UPDATE outbox_messages SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3 WHERE id = $1
`

type MarkPaymentOutboxFailedParams struct {
	ID            string    `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
}

func (q *Queries) MarkPaymentOutboxFailed(ctx context.Context, arg MarkPaymentOutboxFailedParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentOutboxFailed, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const markPaymentOutboxPublished = `-- name: MarkPaymentOutboxPublished :exec
UPDATE outbox_messages SET published_at = $2, last_error = '' WHERE id = $1
`

type MarkPaymentOutboxPublishedParams struct {
	ID          string       `json:"id"`
	PublishedAt sql.NullTime `json:"published_at"`
}

func (q *Queries) MarkPaymentOutboxPublished(ctx context.Context, arg MarkPaymentOutboxPublishedParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentOutboxPublished, arg.ID, arg.PublishedAt)
	return err
}
