// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type InboxMessage struct {
	MessageID   string    `json:"message_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type OutboxMessage struct {
	ID            string          `json:"id"`
	MessageType   string          `json:"message_type"`
	RoutingKey    string          `json:"routing_key"`
	Payload       json.RawMessage `json:"payload"`
	Attempts      int32           `json:"attempts"`
	NextAttemptAt time.Time       `json:"next_attempt_at"`
	PublishedAt   sql.NullTime    `json:"published_at"`
	LastError     string          `json:"last_error"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Payment struct {
	ID          string    `json:"id"`
	OrderID     string    `json:"order_id"`
	AmountCents int64     `json:"amount_cents"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}
