// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreatePaymentInboxMessage(ctx context.Context, arg CreatePaymentInboxMessageParams) error
	CreatePaymentOutboxMessage(ctx context.Context, arg CreatePaymentOutboxMessageParams) error
	GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error)
	ListPendingPaymentOutboxMessages(ctx context.Context, arg ListPendingPaymentOutboxMessagesParams) ([]OutboxMessage, error)
	MarkPaymentOutboxFailed(ctx context.Context, arg MarkPaymentOutboxFailedParams) error
	MarkPaymentOutboxPublished(ctx context.Context, arg MarkPaymentOutboxPublishedParams) error
}

var _ Querier = (*Queries)(nil)
