// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"
	"time"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO customers (id, email, password_hash, roles, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCustomerParams struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Roles        string    `json:"roles"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, createCustomer,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Roles,
		arg.CreatedAt,
	)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, email, password_hash, roles, created_at
FROM customers
WHERE email = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, email, password_hash, roles, created_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.CreatedAt,
	)
	return i, err
}
