// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Customer struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Roles        string    `json:"roles"`
	CreatedAt    time.Time `json:"created_at"`
	Name         string    `json:"name"`
}

type InboxMessage struct {
	MessageID   string    `json:"message_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type Order struct {
	ID               string    `json:"id"`
	CustomerID       string    `json:"customer_id"`
	TotalAmountCents int64     `json:"total_amount_cents"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID             int64  `json:"id"`
	OrderID        string `json:"order_id"`
	ProductID      string `json:"product_id"`
	ProductName    string `json:"product_name"`
	UnitPriceCents int64  `json:"unit_price_cents"`
	Quantity       int32  `json:"quantity"`
}

type OrderSaga struct {
	ID            string    `json:"id"`
	OrderID       string    `json:"order_id"`
	CorrelationID string    `json:"correlation_id"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type OutboxMessage struct {
	ID            string          `json:"id"`
	MessageType   string          `json:"message_type"`
	RoutingKey    string          `json:"routing_key"`
	Payload       json.RawMessage `json:"payload"`
	Attempts      int32           `json:"attempts"`
	NextAttemptAt time.Time       `json:"next_attempt_at"`
	PublishedAt   sql.NullTime    `json:"published_at"`
	LastError     string          `json:"last_error"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Payment struct {
	ID          string    `json:"id"`
	OrderID     string    `json:"order_id"`
	AmountCents int64     `json:"amount_cents"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceCents  int64     `json:"price_cents"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Stock struct {
	ProductID string    `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	UpdatedAt time.Time `json:"updated_at"`
}
