// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
	"time"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (
    id, order_id, amount_cents, status, created_at
)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePaymentParams struct {
	ID          string    `json:"id"`
	OrderID     string    `json:"order_id"`
	AmountCents int64     `json:"amount_cents"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.AmountCents,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
