// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT COUNT(*)
FROM products
WHERE status = 'ACTIVE'
`

func (q *Queries) CountActiveProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price_cents, status, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, description, price_cents, status, created_at, updated_at
FROM products
WHERE status = 'ACTIVE'
ORDER BY created_at DESC
LIMIT $2::integer
OFFSET $1::integer
`

type ListActiveProductsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT id, name, description, price_cents, status, created_at, updated_at
FROM products
WHERE id = ANY($1::text[])
`

func (q *Queries) ListProductsByIDs(ctx context.Context, productIds []string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByIDs, pq.Array(productIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (
    id, name, description, price_cents, status, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price_cents = EXCLUDED.price_cents,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
`

type UpsertProductParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceCents  int64     `json:"price_cents"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.ExecContext(ctx, upsertProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
