// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountActiveProducts(ctx context.Context) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id string) (Customer, error)
	GetOrderByID(ctx context.Context, id string) (Order, error)
	GetProductByID(ctx context.Context, id string) (Product, error)
	GetStockByProductID(ctx context.Context, productID string) (Stock, error)
	GetStockByProductIDForUpdate(ctx context.Context, productID string) (Stock, error)
	ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error)
	ListOrderItemsByOrderIDs(ctx context.Context, orderIds []string) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error)
	ListProductsByIDs(ctx context.Context, productIds []string) ([]Product, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpsertProduct(ctx context.Context, arg UpsertProductParams) error
	UpsertStock(ctx context.Context, arg UpsertStockParams) error
}

var _ Querier = (*Queries)(nil)
