// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sagas.sql

package sqlc

import (
	"context"
	"time"
)

const createOrderSaga = `-- name: CreateOrderSaga :exec
INSERT INTO order_sagas (id, order_id, correlation_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrderSagaParams struct {
	ID            string    `json:"id"`
	OrderID       string    `json:"order_id"`
	CorrelationID string    `json:"correlation_id"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateOrderSaga(ctx context.Context, arg CreateOrderSagaParams) error {
	_, err := q.db.ExecContext(ctx, createOrderSaga,
		arg.ID,
		arg.OrderID,
		arg.CorrelationID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrderSagaForUpdate = `-- name: GetOrderSagaForUpdate :one
SELECT id, order_id, correlation_id, status, created_at, updated_at
FROM order_sagas
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderSagaForUpdate(ctx context.Context, id string) (OrderSaga, error) {
	row := q.db.QueryRowContext(ctx, getOrderSagaForUpdate, id)
	var i OrderSaga
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CorrelationID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderSaga = `-- name: UpdateOrderSaga :exec
UPDATE order_sagas SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateOrderSagaParams struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrderSaga(ctx context.Context, arg UpdateOrderSagaParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderSaga, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
