// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stocks.sql

package sqlc

import (
	"context"
	"time"
)

const getStockByProductID = `-- name: GetStockByProductID :one
SELECT product_id, quantity, updated_at
FROM stocks
WHERE product_id = $1
`

func (q *Queries) GetStockByProductID(ctx context.Context, productID string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByProductID, productID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const getStockByProductIDForUpdate = `-- name: GetStockByProductIDForUpdate :one
SELECT product_id, quantity, updated_at
FROM stocks
WHERE product_id = $1
FOR UPDATE
`

func (q *Queries) GetStockByProductIDForUpdate(ctx context.Context, productID string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByProductIDForUpdate, productID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const upsertStock = `-- name: UpsertStock :exec
INSERT INTO stocks (product_id, quantity, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (product_id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    updated_at = EXCLUDED.updated_at
`

type UpsertStockParams struct {
	ProductID string    `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) error {
	_, err := q.db.ExecContext(ctx, upsertStock, arg.ProductID, arg.Quantity, arg.UpdatedAt)
	return err
}
